patched otbr, hard reset of mdns and gui disabled

diff --git a/third-party/patches/new_otbr.patch b/third-party/patches/new_otbr.patch
--- a/third-party/patches/new_otbr.patch
+++ b/third-party/patches/new_otbr.patch
@@ -1,24 +1,24 @@
-From e10c150dc4c9d84cbb77fd36c4249c8bcbd6eece Mon Sep 17 00:00:00 2001
-From: JakoCrafter <j.heirweghjh.jh@gmail.com>
-Date: Thu, 13 Nov 2025 21:15:50 +0100
-Subject: [PATCH] new_otbr
+From 58c9e0fba37e54c131ec9619e25261824ed44542 Mon Sep 17 00:00:00 2001
+From: Test Test <test@test.com>
+Date: Wed, 25 Mar 2026 13:16:49 +0000
+Subject: [PATCH] fix
 
 ---
- CMakeLists.txt                          |  5 +--
- script/_dhcpv6_pd                       | 52 ++++++++++++------------
- script/_disable_services                | 18 ++++-----
- script/_dns64                           | 38 ++++++++---------
- script/_firewall                        | 14 +++----
- script/_nat64                           | 32 +++++++--------
- script/_network_manager                 | 25 ++++++------
- script/_otbr                            | 50 +++++++++++------------
+ CMakeLists.txt                          |  5 +-
+ script/_dhcpv6_pd                       | 52 ++++++++++-----------
+ script/_disable_services                | 18 ++++----
+ script/_dns64                           | 38 +++++++--------
+ script/_firewall                        | 14 +++---
+ script/_nat64                           | 32 ++++++-------
+ script/_network_manager                 | 25 +++++-----
+ script/_otbr                            | 50 ++++++++++----------
  script/console                          |  6 +--
- script/server                           | 48 +++++++++++-----------
- src/agent/CMakeLists.txt                | 21 ++++++++++
- src/agent/coverage_listener/zmq_cov.cpp | 54 +++++++++++++++++++++++++
- src/agent/coverage_listener/zmq_cov.h   | 12 ++++++
- src/agent/main.cpp                      | 39 ++++++++++++++++++
- 14 files changed, 270 insertions(+), 144 deletions(-)
+ script/server                           | 61 +++++++++++++------------
+ src/agent/CMakeLists.txt                | 21 +++++++++
+ src/agent/coverage_listener/zmq_cov.cpp | 54 ++++++++++++++++++++++
+ src/agent/coverage_listener/zmq_cov.h   | 12 +++++
+ src/agent/main.cpp                      | 39 ++++++++++++++++
+ 14 files changed, 277 insertions(+), 150 deletions(-)
  create mode 100644 src/agent/coverage_listener/zmq_cov.cpp
  create mode 100644 src/agent/coverage_listener/zmq_cov.h
 
@@ -468,10 +468,10 @@ index 416dd024..54016172 100755
  
      trap on_exit INT TERM EXIT
 diff --git a/script/server b/script/server
-index b4eaedfb..09ec07f1 100755
+index b4eaedfb..db1cb30d 100755
 --- a/script/server
 +++ b/script/server
-@@ -44,23 +44,23 @@ startup()
+@@ -44,23 +44,24 @@ startup()
      nat64_start || die 'Failed to start NAT64!'
      dns64_start || die 'Failed to start DNS64!'
      firewall_start || die 'Failed to start firewall'
@@ -484,30 +484,34 @@ index b4eaedfb..09ec07f1 100755
 -    elif have service; then
 -        sudo service rsyslog status || sudo service rsyslog start || die 'Failed to start rsyslog!'
 -        sudo service dbus status || sudo service dbus start || die 'Failed to start dbus!'
-+    # if have systemctl; then
-+    #     systemctl is-active rsyslog || sudo systemctl start rsyslog || die 'Failed to start rsyslog!'
-+    #     systemctl is-active dbus || sudo systemctl start dbus || die 'Failed to start dbus!'
-+    #     systemctl is-active avahi-daemon || sudo systemctl start avahi-daemon || die 'Failed to start avahi!'
-+    #     without WEB_GUI || systemctl is-active otbr-web || sudo systemctl start otbr-web || die 'Failed to start otbr-web!'
-+    #     systemctl is-active otbr-agent || sudo systemctl start otbr-agent || die 'Failed to start otbr-agent!'
-+    # elif have service; then
-+        # sudo service rsyslog status || sudo service rsyslog start || die 'Failed to start rsyslog!'
-+        # sudo service dbus status || sudo service dbus start || die 'Failed to start dbus!'
-         # Tolerate the mdns failure as it is installed for only CI docker.
-         sudo service mdns status || sudo service mdns start || echo "service mdns is not available!"
+-        # Tolerate the mdns failure as it is installed for only CI docker.
+-        sudo service mdns status || sudo service mdns start || echo "service mdns is not available!"
++    # if have systemctl; then													# THREADFUZZ: dont use systemctl
++    
++    #     systemctl is-active rsyslog || sudo systemctl start rsyslog || die 'Failed to start rsyslog!'				# THREADFUZZ: dont use systemctl
++    #     systemctl is-active dbus || sudo systemctl start dbus || die 'Failed to start dbus!'					# THREADFUZZ: dont use systemctl
++    #     systemctl is-active avahi-daemon || sudo systemctl start avahi-daemon || die 'Failed to start avahi!'			# THREADFUZZ: dont use systemctl
++    #     without WEB_GUI || systemctl is-active otbr-web || sudo systemctl start otbr-web || die 'Failed to start otbr-web!'	# THREADFUZZ: dont use systemctl
++    #     systemctl is-active otbr-agent || sudo systemctl start otbr-agent || die 'Failed to start otbr-agent!'		# THREADFUZZ: dont use systemctl
++    # elif have service; then													# THREADFUZZ: dont use systemctl			
++        # sudo service rsyslog status || sudo service rsyslog start || die 'Failed to start rsyslog!'				# THREADFUZZ: well use own rsyslog
++        # sudo service dbus status || sudo service dbus start || die 'Failed to start dbus!'					# THREADFUZZ: use dbus of host 
++        # Tolerate the mdns failure as it is installed for only CI docker.							
++        sudo service mdns start || echo "service mdns is not available!"							# THREADFUZZ: check status is broken
          sudo service avahi-daemon status || sudo service avahi-daemon start || die 'Failed to start avahi!'
          sudo service otbr-agent status || sudo service otbr-agent start || die 'Failed to start otbr-agent!'
-         without WEB_GUI || sudo service otbr-web status || sudo service otbr-web start || die 'Failed to start otbr-web!'
+-        without WEB_GUI || sudo service otbr-web status || sudo service otbr-web start || die 'Failed to start otbr-web!'
 -    else
 -        die 'Unable to find service manager. Try script/console to start in console mode!'
 -    fi
++        # without WEB_GUI || sudo service otbr-web status || sudo service otbr-web start || die 'Failed to start otbr-web!'	# THREADFUZZ: don't enable the gui
 +    # else
 +    #     die 'Unable to find service manager. Try script/console to start in console mode!'
 +    # fi
      # shellcheck source=/dev/null
      . "$AFTER_HOOK"
  }
-@@ -70,22 +70,22 @@ shutdown()
+@@ -70,22 +71,22 @@ shutdown()
      nat64_stop || echo 'Failed to stop NAT64!'
      dns64_stop || echo 'Failed to stop DNS64!'
      firewall_stop || echo 'Failed to stop firewall'
@@ -520,22 +524,25 @@ index b4eaedfb..09ec07f1 100755
 -    elif have service; then
 -        sudo service rsyslog status && sudo service rsyslog stop || echo 'Failed to stop rsyslog!'
 -        sudo service dbus status && sudo service dbus stop || echo 'Failed to stop dbus!'
-+    # if have systemctl; then
-+    #     systemctl is-active rsyslog && sudo systemctl stop rsyslog || echo 'Failed to stop rsyslog!'
-+    #     systemctl is-active dbus && sudo systemctl stop dbus || echo 'Failed to stop dbus!'
-+    #     systemctl is-active avahi-daemon && sudo systemctl stop avahi-daemon || echo 'Failed to stop avahi!'
-+    #     without WEB_GUI || systemctl is-active otbr-web && sudo systemctl stop otbr-web || echo 'Failed to stop otbr-web!'
-+    #     systemctl is-active otbr-agent && sudo systemctl stop otbr-agent || echo 'Failed to stop otbr-agent!'
-+    # elif have service; then
-+        # sudo service rsyslog status && sudo service rsyslog stop || echo 'Failed to stop rsyslog!'
-+        # sudo service dbus status && sudo service dbus stop || echo 'Failed to stop dbus!'
-         sudo service mdns status && sudo service mdns stop || echo "service mdns is not available!"
-         sudo service avahi-daemon status && sudo service avahi-daemon stop || echo 'Failed to stop avahi!'
+-        sudo service mdns status && sudo service mdns stop || echo "service mdns is not available!"
+-        sudo service avahi-daemon status && sudo service avahi-daemon stop || echo 'Failed to stop avahi!'
++    # if have systemctl; then# THREADFUZZ: dont use systemctl
++    #     systemctl is-active rsyslog && sudo systemctl stop rsyslog || echo 'Failed to stop rsyslog!'				# THREADFUZZ: dont use systemctl
++    #     systemctl is-active dbus && sudo systemctl stop dbus || echo 'Failed to stop dbus!'					# THREADFUZZ: dont use systemctl
++    #     systemctl is-active avahi-daemon && sudo systemctl stop avahi-daemon || echo 'Failed to stop avahi!'			# THREADFUZZ: dont use systemctl
++    #     without WEB_GUI || systemctl is-active otbr-web && sudo systemctl stop otbr-web || echo 'Failed to stop otbr-web!'	# THREADFUZZ: dont use systemctl
++    #     systemctl is-active otbr-agent && sudo systemctl stop otbr-agent || echo 'Failed to stop otbr-agent!'			# THREADFUZZ: dont use systemctl
++    # elif have service; then													# THREADFUZZ: dont use systemctl
++        # sudo service rsyslog status && sudo service rsyslog stop || echo 'Failed to stop rsyslog!'				# THREADFUZZ: well use own rsyslog
++        # sudo service dbus status && sudo service dbus stop || echo 'Failed to stop dbus!'					# THREADFUZZ: use dbus of host
++        sudo service mdns stop || echo "service mdns is not available!"								# THREADFUZZ: check status is broken
++        sudo service avahi-daemon status && sudo service avahi-daemon stop || echo 'Failed to stop avahi!'		
          sudo service otbr-agent status && sudo service otbr-agent stop || echo 'Failed to stop otbr-agent!'
-         without WEB_GUI || sudo service otbr-web status && sudo service otbr-web stop || echo 'Failed to stop otbr-web!'
+-        without WEB_GUI || sudo service otbr-web status && sudo service otbr-web stop || echo 'Failed to stop otbr-web!'
 -    else
 -        echo 'Unable to find service manager. Try script/console to stop in console mode!'
 -    fi
++        # without WEB_GUI || sudo service otbr-web status && sudo service otbr-web stop || echo 'Failed to stop otbr-web!'	# THREADFUZZ: don't enable the gui
 +    # else
 +    #     echo 'Unable to find service manager. Try script/console to stop in console mode!'
 +    # fi
@@ -727,5 +734,6 @@ index bc082ca6..8a3dc70a 100644
  }
  
 -- 
-2.43.0
+2.34.1
+
 
